---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment
spec:
  template:
    spec:
      lkj: |
          alpha
          beta
      containers:
      - name: container_without_image
        imagePullPolicy: never
        ports:
        - containerPort: 80
      - name: container_with_image
        image: nginy
        isRoot: false
        ports:
        - containerPort: 81

