---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment
spec:
  template:
    spec:
      # Comment that should be kept
      multiline_field: |
          alpha
          beta
      containers:
      - name: container_without_image
        imagePullPolicy: never
        ports:
        - containerPort: 80

      - name: container_with_image
        image: nginx
        isRoot: false
        may_be_unwanted: 
          unwanted: false
        ports:
        - containerPort: 81
        credentials: 
          scheme: none

      - name: other_initial_types
        imagePullPolicy: false
        isRoot: 13
        may_be_unwanted: 
          unwanted: true
        ports:
        - containerPort: 80
        credentials: 18

      - name: container_to_remove
        to_remove: true
        imagePullPolicy: always
        ports:
        - containerPort: 80